### ISSUE TITLE
Issue with nested objects in variables

### ISSUE THREAD

**Issue by gokulp-rn** [aerogear/offix#1054]
## Bug Report

* **Platform (e.g. Android/iOS)**: Android & Ios
* **Affected Package(s)**: offix-cache
* **Package version(s)**: 0.15.0
* **Framework**: React-native

I am creating a transaction in offline with data:
```javascript
{
  amount: 100,
  product:[
    {name: "Apple", quantity:"10"},
    {name: "Orange", quantity:"5"}
  [
}
```

And updating the same in offline (Just changing the quantity)
```javascript
{
  id: "client:a121ss1313d1"
  amount: 100,
  product:[
    {name: "Apple", quantity:"5"},
    {name: "Orange", quantity:"5"}
  [
}
```
In this case `Apple and Orange` get duplicated because i am not able to pass `id` of those while updating.

Offix can handle the `id` of nested data like doing for data at highlevel?

**Comment by kingsleyzissou** [comment]
HI @gokulp-rn

So relationships get a little bit tricky. Do you have a type defined for your product object?

Here is an example from our `datasync-starter` repo:
https://github.com/aerogear/datasync-starter/blob/master/client/src/graphql/generated.ts

We then have a mutation that we create specifically for that type:
https://github.com/aerogear/datasync-starter/blob/3a19b1e580df3abb76334e4ba7033113505dc47f/client/src/pages/ViewTaskPage.tsx#L24

Rather than updating the parent object

**Comment by kingsleyzissou** [comment]
Hi @gokulp-rn, we have made the decision to move away from the Apollo client and we have decided to deprecate our Offix packages and release our Datastore. I will be closing this issue, but if you have any questions, please feel free to let us know.

You can see the docs for the updated datastore here:
https://offix.dev/docs/getting-started
