### ISSUE TITLE
Request: make it easier to create and access OfflineClient.apolloClient

### ISSUE THREAD

**Issue by darahayes** [aerogear/offix#136]
## Feature Request

Related discussion here: https://github.com/darahayes/offix-example-react/issues/1

**Is your feature request related to a problem? Please describe.**

The main problem right now is that the flow to create a client looks something like this.

```js
let client = new OfflineClient(config);
await client.init();
let apolloClient = client.apolloClient
```

The apolloClient is really what we're looking for but it doesn't become available to us until after we `await client.init()`. I noticed while trying to build a react application that the main way to pass an ApolloClient around a React application is to use an `ApolloProvider` either from `react-apollo-hooks` or `react-apollo`.

Example:

```js
import React from 'react';
import { render } from 'react-dom';

import { ApolloProvider } from 'react-apollo-hooks';

const client = ... // create Apollo client

const App = () => (
  <ApolloProvider client={client}>
    <MyRootComponent />
  </ApolloProvider>
);

render(<App />, document.getElementById('root'))
```

Now [`useApolloClient`](https://github.com/trojanowski/react-apollo-hooks#useapolloclient) can be used within components.

The problem is that `ApolloProvider` **must be passed a client** and you can't really `await` for things during a component render.

[The hacky solution](https://github.com/darahayes/offix-example-react/blob/847cb18ce159c08b31f4efa9cc0d9d38ac220f60/src/components/App.tsx#L35-L62) I found so far was to create a regular apollo client, inject that into my application, and use a hook to swap out the regular client with the one coming from Offix after the `init` has completed.

**Describe the solution you'd like**
Ideally we would have one of two fixes:

* `OfflineClient.init()` synchronously returns the ApolloClient.
* `OfflineClient` extends `ApolloClient` and somehow everything can be synchronously set up in the constructor.

I think I would actually prefer the first option for now because it's less of a drastic change.

**Comment by wtrocki** [comment]
There are couple reasons why we are async but main one is that we need to restore the cache. However, this should not be associated with the client. 

In fact, we can create a client before and have the internal promise that will be checked if client was rehydrated before executing first query or mutate inside application. This is how this could look like:

https://github.com/apollographql/apollo-cache-persist/issues/88

> The problem is that ApolloProvider must be passed a client and you can't really await for things during a component render.

I think we can, because this is how apollo-cache-perist examples are done but it generates a lot of overhead that developers do not like: 
https://github.com/apollographql/apollo-cache-persist/issues/61

Example how this can be done: https://github.com/aerogear/offline-conflict-strategies/blob/master/web/src/App.js#L14-L31

However I personally do not believe that this will give us really good api. 
I think users should create client first and then have extra methods:

client.hydrated - to check if cache was restored
client.replicateOffflineData - to manually replicate offline data (we do that now when client is created which is causing many issues.

I think we need to think about the great user API first, before we address this issue and main elements we should be focusing on are:


- Are we using plain apollo client with an additional ` method that can be passed to provider?

- Do we have capacity to provide our own react specific library or we can get away with some sample application

- Do we want to support more than just apollo client - this could reduce the number of issues and reduce problems with cache helpers etc.

**Comment by darahayes** [comment]
@wtrocki I did a little bit more research around the example apollo-cache-persist provides: https://github.com/apollographql/apollo-cache-persist#react

So this seems pretty good to me. I decided to implement a similar approach but using the `useEffect` hook which can be a much cleaner and concise way to achieve the same behaviour as `componentDidMount`.

Take a look at this PR I have here: https://github.com/darahayes/offix-example-react/pull/2

To be quite honest, I would be pretty happy with the approach I have in that example application. I think it would be really nice if we could at least document that somewhere as a first step

**Comment by wtrocki** [comment]
@darahayes Can I ask you to update status here. We have done some research and have now new package added.

**Comment by wtrocki** [comment]
I think bigger discussion is needed how we can get the API right

**Comment by wtrocki** [comment]
The solution for this will be to make the persistence and restoration process controlled by the user.
We are really close of doing this in current work.

**Comment by darahayes** [comment]
Having worked on the offix-client package for sometime, I believe for the time being there isn't much we can do about client.init() being an async function. The main reason for this is initializing the persistence layer is asynchronous.

Additionally, in the context of React I've found that waiting for some state to be asynchronously initialized (such as the apollo client) before passing it into a provider seems to be a pretty common pattern.

Going to close this now.
