### ISSUE TITLE
Validate config at runtime

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#283]
## Feature Request

Idea is to use runtime interface checker for js code

https://github.com/gristlabs/ts-interface-checker

**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by Eunovo** [comment]
Please assign this to me

**Comment by Eunovo** [comment]
@wtrocki To be clear about what you want I'm using an example. You want this config [here](https://github.com/aerogear/offix/blob/bc958d42297f1227c11a93b9ac7ccc6c2bcecc72/packages/offix-scheduler/src/OffixScheduler.ts#L54)  to be validated before it is used because if this library is used in js project, an invalid config can be passed

**Comment by wtrocki** [comment]
I'm more into some basic validation for ApolloConfig that is initalized here:
https://github.com/aerogear/offix/blob/bc958d42297f1227c11a93b9ac7ccc6c2bcecc72/packages/offix-client/src/ApolloOfflineClient.ts#L50
