### ISSUE TITLE
Add support for useQuery and useMutation for react-offix-hooks

### ISSUE THREAD

**Issue by kunaldodiya** [aerogear/offix#293]
Add support for useQuery, useMutation and useSubscription for react-offix-hooks,

currently it has only useOfflineHooks but for queries we need to import from original react-hooks, managing hooks from 2 different library is cumbersome, please add support so that we can import all in one library :)

**Comment by wtrocki** [comment]
That will be our no1 priority for next release.

**Comment by wtrocki** [comment]
Ping @darahayes

**Comment by darahayes** [comment]
@kunaldodiya One of the main reasons we did it this way is because `@apollo/react-hooks` is not the only React hooks library available for Apollo Client. As a team we decided to provide our own implementation for the offline functionality and then allow users have the flexibility to choose which pre existing hooks library they want for all other operations (mutations, queries, subscriptions) and not force them to import packages they possibly do not require. 

I'm going to close this issue for now, but if you feel strongly about it, you are more than welcome to reopen it and we can have a discussion.
