### ISSUE TITLE
Entities ids cache update workflow

### ISSUE THREAD

**Issue by lucasmez** [aerogear/offix#367]
_This is not a bug report or a new feature idea, it is a question about cache update workflow for an offline app using Offix, so I apologize if I added this issue using the wrong label_

I am building an offline-first application that lets users switch between offline and online modes, and Offix looked like a very good solution for what I needed, until I ran into a problem: 

Users can create items in a nested list like so:

![Image of Yaktocat](http://maxdesign.com.au/maxdesign/wp-content/uploads/2015/04/folder-metaphor2.png) 

The GraphQL mutation I use to create items has the following signature: **CreateItem(itemTitle, parentId)** , parentId being the id of the item where the newly created item will be placed under. So, for example, to create the "sub-item 1" in the image above, I'd call **CreateItem("sub-item 1", <item 4 id>)**  Entities Ids must be generated by the database on the back-end instead of using client-generated ones.

I'm using Offix's OptimisticResponse helper, which generates an unique Id for each item using the  _client:UUID_ format.
If a users creates many nested items while offline, Offix will queue up many mutations with the second parameters (parentId) being populated with the Offix-generated ids. As soon as the user switches to online-mode, I assume those mutations will be sent to the server in parallel (with limitations imposed by the browser). But all of the parentIds for the mutations will still be the Offix-generated ids, which will result in the API returning an error for all of them, because entities with those parentIds do not exist in the database.

With that in mind, and assuming it is correct, here is the workflow I want to implement when a user creates items:

1. _User switches to Offline Mode._
2. _User creates many new items._
2. optimisticResponses  with client-generated ids are created for all of them.
3. Inside the CreateItem mutation update() function:
       `Add all optimistic responses to the cache using writeFragment() and writeQuery() so that components using useQuery() will be reactively updated`
4. _User can close/refresh the page many times. Offline data won't be lost since the optimistic responses were all cached in the persistent store._
4. _User switches to Online Mode._
5. Many mutations will be queued up by Offix. **Send them to the server asynchronously in series**. After each mutation call returns, and before sending the next one, do the following:
    `Replace all references to the client-generated ids from the call that just returned, with the real id returned from the server.`
    
      Example: Using the image above as reference, say there are 2 mutations queued up: 
      - _CreateItem("sub item 3", <real item 4 id>)_,  having a client-generated id of _client:subitem3_. 
      - _CreateItem("sub sub item 1", "client:subitem3")_, having a client-generated id of _client:subsub1_.

    The first mutation will work since <real item 4 id> exists in the database. The second will fail since "client:subitem3" id was client-generated and it doesn't exist in the database. So, as soon as the first mutation returns, and before any other are sent, all references to "client:subitem3" in the queue will be replaced with the real id contained in the first mutation's API response. So the second mutation now becomes:
    - _CreateItem("sub item 3", < real id returned from first mutation >)_,  having a client-generated id of _client:subitem3_. 

    And the same process will happen for every CreateItem mutation.

6. The CreateItem mutation update() function will be called again, this time with the actual responses from the server. Inside it, do:
      `Replace client-generated id for the entity *everywhere* it appears in the cache with the real entity id returned from the API.` (this could be a performance bottleneck)

Does this workflow makes sense for an app that has online and offline modes where users may be offline for months before synching their changes? Is it possible to acheive it using Offix? Can I control the mutation queue behavior to achieve that? Is it recommended to update the cache using optimisticResponses?

Thank you!

**Comment by wtrocki** [comment]
@lucasmez Thank you so much for very detailed definition of the problem. We will need some time to get back to you with solution.

Offix have limited capabilities at the moment in terms of cache updates for nested elements, in caches queries but looking to improve this in very short time. 

For offline queue we do try to remap client generated id's but that only happens if:
- mutation has no nested input types
- Create operation returns exact object with id present.

Offline mutations are kept as linked list and send in sequence to assume order - create before edit and also conflict handling.
The way this should work is that after offline operation is finished we should be able to rewrite items in list to new id's. We currently do that for id's but not parentId as this is related to business logic that we cannot do out of the box.

This issue was mentioned before and we talked about it today with @kingsleyzissou who needed to write his own queue handler to rewrite elements in queue. While this is possible now it seems hacky so we might need to have chat about this and see if we can have some generic engine that will handle local client id rewrites

**Comment by wtrocki** [comment]
Mentioned workaround https://github.com/aerogear/ionic-showcase/commit/858ede92b982de6dbc82732c006c54d7559ff99d

**Comment by lucasmez** [comment]
@wtrocki Thank you for the fast response and for linking that workaround!  I will try using the `registerOfflineEventListener()` method.  Will the listeners I add using that method overwrite the following default listeners present in the ApolloOfflineClient?
```

this.queue.registerOfflineQueueListener({
      onOperationEnqueued: (operation: ApolloQueueEntryOperation) => {
        addOptimisticResponse(this, operation);
      },
      onOperationSuccess: (operation: ApolloQueueEntryOperation, result: FetchResult) => {
        replaceClientGeneratedIDsInQueue(this.scheduler.queue.queue, operation, result);
        removeOptimisticResponse(this, operation);
      },
      onOperationFailure: (operation: ApolloQueueEntryOperation, error) => {
        removeOptimisticResponse(this, operation);
      },
      onOperationRequeued: (operation: ApolloQueueEntryOperation) => {
        if (this.mutationCacheUpdates) {
          restoreOptimisticResponse(this, this.mutationCacheUpdates, operation);
        }
      }
    });
```


Let's say I don't want Offix to remove optimistic responses when an operation fails. Can I just overwrite the `onOperationFailure()`  and provide an empty body?

```
   onOperationFailure: (operation: ApolloQueueEntryOperation, error) => {
       
      },
```
Or will the default one still be called?

**Comment by wtrocki** [comment]
As for hacks - All listeners in queue will be called but nothing stopping us to flush existing ones and attach new one. It happens that they are public and can be accessed from client 

https://github.com/aerogear/offix/blob/master/packages/offix-scheduler/src/queue/OfflineQueue.ts#L55

Obviously this is just us trying hard to get this to work in really convoluted way. I would love to have more time and figure out how we can fix this right so no such hacks are needed.

Do not thank me. It was @kingsleyzissou who also found this problem and came with fix.

**Comment by lucasmez** [comment]
@wtrocki Just a suggestion regarding the problem of nested updates, where "parentIds" in the queue should be updated once a mutation returns from the server (in addition to the regular id field), maybe it'd be worthwile having Offix accept an array of id names to replace in the queue. For example:

We would pass this option to Offix:

`const idsToReplace = ["parentId", "anotherId"];`

Then the `replaceClientGeneratedIDsInQueue()` method, in addition to replacing the "idField" variables for the mutations in the queue, would also replace fields with the names added above.

Not sure if this is a common enough problem to warrant the change, but I'll try doing this for my case.

**Comment by darahayes** [comment]
@lucasmez thanks for opening an issue with such detail. I see you found `replaceClientGeneratedIdsInQueue.`

> maybe it'd be worthwile having Offix accept an array of id names to replace in the queue.

This is a reasonable idea, but we've found other issues with the `replaceClientGeneratedIDsInQueue` method. For example, it assumes your `variables` is a flat object like this:

```
// the mutation operation in the queue
{
  mutation: {...},
  context: {...},
  variables: {
    id: "client:123",
    parentId: "client:456",
    name: "todo item"
    ...
  }
}
```

While it's actually pretty common to use input types where your variables will be nested under another key:

```
{
  variables: {
    input: {
      id: "client:123",
      parentId: "client:456",
      name: "todo item"
      ...
    }
  }
}
```

and in that case the function stops working as intended. 

I see two approaches to the problem.

1. We used to have a concept of result processors in Offix. You could pass a function that would be executed on successful mutations. It would have access to the queue and the original operation and the results. The `replaceClientGeneratedIdsInQueue` was originally a `ResultProcessor`. 

As an end user, writing the code to do this will work but I think it has the potential to become really messy. Most likely you'll have to supply a single function to the client constructor that can process the results for all your different mutations, handling various different cases like yours. What if you have similar requirements for multiple different types in your application. You couldn't really pass a specific function for a given operation at the time of calling `client.offlineMutate` because we need to support application restarts. We can't really persist javascript code across restarts.
 
2. Your suggestion about passing a list of keys for fields that need to be updated is really nice and user friendly because you could pass those for a specific `client.offlineMutate` call and we could add those to a given operation in the queue. However, we'd need to be able to handle the challenge I mentioned about input types in a generic way. It could mean that you could pass something like this `['input.id', 'input.parentId']`.

I'd personally like to implement the second approach because it's less work for the user for this specific use case, but I worry that some new requirements will come up later on that force us to implement something like the first approach on top of that.

**Comment by wtrocki** [comment]
Let's go with result processors. We can have variation per type or global and implement default ones that will be helpfull for common cases.

**Comment by kingsleyzissou** [comment]
@darahayes I'm plus one for the second approach, would allow for a little bit more flexibility, that's if we're not forced to implement the first approach.

**Comment by kingsleyzissou** [comment]
I am also getting a weird error with re-queuing the optimistic response. The operation.op that is being passed through to the `restoreOptimisticResponse` method is undefined.

**Comment by lucasmez** [comment]
@kingsleyzissou I saw that error yesterday too while trying to register my own registerOfflineQueueListeners. I thought I was doing something wrong so I didn't mention it =p.
