### ISSUE TITLE
Using it with Vue Apollo? Can I?

### ISSUE THREAD

**Issue by frederikhors** [aerogear/offix#868]
I just discovered this project.

Congratulations, great job!

A question that I have not found an answer to in the docs: are there any problems if I use it with https://apollo.vuejs.org?

**Comment by wtrocki** [comment]
https://github.com/apollographql/apollo-cache-persist can be used with vue and it will give you read only offline capabilities. 

As for Apollo client it is generic. Works with any JS context and we have react helpers because of... react. Not that much a Vue person but it seems that this might work normally.

**Comment by mmouterde** [comment]
@frederikhors Have you finally tried with VueApollo ?

**Comment by MitchellMonaghan** [comment]
This is kind of late, but I am using offix with vue and vue-apollo

**Comment by wtrocki** [comment]
We haven't tested it
